Chainlit/literalai-docs

concepts/dataset.mdx, mint.json, python-client/api-reference/dataset.mdx, typescript-client/api-reference/dataset.mdx
- Add the dataset concept
- Add the python api reference for dataset
- Add the typescript api reference for dataset
=> Add dataset to the SDK

self-hosting/deployment.mdx
- Add missing requirements for Azure storage.
=> Add pgcrypto requirements

concepts/project-roles.mdx, concepts/prompt.mdx
- Add a credentials section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/36)
=> Add Shared Credentials security paragraph on Projects and roles

integrations/vercel-ai-sdk.mdx, mint.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/40)
=> feat: add integration page for vercel ai sdk

integrations/openai.mdx
Documentation for https://github.com/Chainlit/typescript-client/pull/17 & https://github.com/Chainlit/python-client/pull/63
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/32)
=> feat: Add tags for openai instrumentation

mint.json, more/export-data.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/44)
=> eng-1297: add export data page

mint.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/48)
=> move score page

more/release-notes.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/49)
=> add release notes 0.0.605-beta

guides/tutorials/evaluating-context-relevancy.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/53)
=> eng-1353 rename intermediary step to output

more/release-notes.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/54)
=> add release notes 606

concepts/evaluation/experiment.mdx, guides/github-cookbook/evaluation.mdx, guides/tutorials/evaluating-context-relevancy.mdx, guides/tutorials/evaluating-user-satisfaction.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/60)
=> fix links to cookbooks

concepts/evaluation/dataset.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/57)
=> Change undefined sdk variable to literal_client

typescript-client/development/changelog.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/64)
=> ENG-1447 update changelog TS client

python-client/development/changelog.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/65)
=> ENG-1446 update changelog python client

guides/tutorials/nextjs-openai-chatbot.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/67)
=> fix: punctuation

more/release-notes.mdx, python-client/development/changelog.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/71)
=> add release notes

self-hosting/deployment.mdx, self-hosting/get-started.mdx
:warning: Plz do not merge as this needs to be coordinated across other repositories :warning:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/68)
=> docs: adapt documentation for self-hosting

concepts/prompt/prompt-api.mdx, concepts/prompt/prompt-playground.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/62)
=> eng-1423 clarify prompt name is id

more/release-notes.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/72)
=> update release notes 0.0.608-beta

concepts/observability/thread.mdx, concepts/observability/user.mdx, guides/observability/agent-run.mdx, guides/observability/conversational-agent-fastapi.mdx, guides/observability/conversational-agent.mdx, guides/prompt/prompt-format.mdx, guides/tutorials/ab-testing-client-side.mdx, guides/tutorials/nextjs-openai-chatbot.mdx, self-hosting/deployment.mdx, self-hosting/get-started.mdx
More explanation on Participant ID filter, as well as some "LiteralAI"->"Literal AI" name fixes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/73)
=> participantId filter

concepts/observability/step.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/78)
=> fix: explain that llm steps require messages/prompt field

get-started/installation.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/79)
=> feat: add Hello world thread in Installation

more/release-notes.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/77)
=> update release notes 609

more/release-notes.mdx
- Wrote the release note based on https://chainlit.slack.com/archives/C05A89EUXMM/p1719223336455249
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Chainlit/literal-docs/80)
=> chore: update release note 0.0.610-beta

mint.json
Fixing the issue https://github.com/Chainlit/literal-docs/issues/81
=> fix: broken links

concepts/settings/project-roles.mdx
=> feat: update the documentation with RBAC

python-client/get-started/introduction.mdx
=> fix: doc singleton

python-client/abstractions/step.mdx, python-client/api-reference/api.mdx, python-client/api-reference/client.mdx, typescript-client/api-reference/dataset.mdx
- reference root run id
- reference `datasetItem.stepId`
=> chore: update sdks to send the root run

more/release-notes.mdx
=> chore: update release notes for 0.0.620-beta

more/release-notes.mdx, python-client/development/changelog.mdx
=> chore: document release notes

more/release-notes.mdx, self-hosting/deployment.mdx
=> chore: add release notes for 0.0.626-beta

more/release-notes.mdx
=> chore: release notes for 0.0.627-beta

guides/logs.mdx
=> feat: add release param

more/release-notes.mdx
=> chore: release notes 0.0.629-beta

python-client/development/changelog.mdx, typescript-client/development/changelog.mdx
=> chore: log changes sdks

more/release-notes.mdx
=> fix: release notes 0.1.2-beta

guides/logs.mdx
=> fix: bind user to thread

more/release-notes.mdx
=> chore: release notes 0.1.4-beta

more/release-notes.mdx
- Add changelog for the version 0.1.5-beta
=> chore: add release note for 0.1.5-beta
